---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-targaryen-resource-controller-sigs-v1-syrax
  failurePolicy: Fail
  name: msyrax.kb.io
  rules:
  - apiGroups:
    - targaryen.resource.controller.sigs
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - syraxes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-targaryen-resource-controller-sigs-v1-syrax
  failurePolicy: Fail
  name: vsyrax.kb.io
  rules:
  - apiGroups:
    - targaryen.resource.controller.sigs
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - syraxes
  sideEffects: None
