---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - targaryen.resource.controller.sigs
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - targaryen.resource.controller.sigs
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - targaryen.resource.controller.sigs
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - targaryen.resource.controller.sigs
  resources:
  - syraxs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - targaryen.resource.controller.sigs
  resources:
  - syraxs/finalizers
  verbs:
  - update
- apiGroups:
  - targaryen.resource.controller.sigs
  resources:
  - syraxs/status
  verbs:
  - get
  - patch
  - update
