apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-bazar-01--john-snow--546
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      dracary: ghj
  template:
    metadata:
      labels:
        dracary: ghj
    spec:
      containers:
        - command:
            - /root/binary
            - start
          image: hiranmoy36/book-bazar
          imagePullPolicy: Always
          name: ros2
      restartPolicy: Always
