apiVersion: targaryen.resource.controller.sigs/v1
kind: Syrax
metadata:
  name: book-bazar-01
spec:
  deletionPolicy: Delete
  deploymentSpec:
    replicas: 2
    name: john-snow
    image: hiranmoy36/book-bazar
    commands: ["/root/binary","start"]
  serviceSpec:
    port: 8080
